#!/bin/bash
# setup-sshfs-key.sh — Run ONCE on your Mac host
# Creates a restricted SSH key for OpenClaw container → host SFTP access
set -e

SSHFS_DIR="$HOME/.openclaw/sshfs"
KEY_FILE="${SSHFS_DIR}/id_ed25519"
AUTH_KEYS="$HOME/.ssh/authorized_keys"
SSHD_CONFIG_DIR="/etc/ssh/sshd_config.d"
SSHD_CONF="${SSHD_CONFIG_DIR}/openclaw-hardening.conf"

echo "=== OpenClaw SSHFS Key Setup ==="
echo ""

# ─── Step 1: Generate SSH key ────────────────────────────────
mkdir -p "$SSHFS_DIR"
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

if [ -f "$KEY_FILE" ]; then
    echo "✓ Key already exists at ${KEY_FILE}"
else
    ssh-keygen -t ed25519 -f "$KEY_FILE" -N "" -C "openclaw-sshfs"
    echo "✓ Generated new key pair at ${KEY_FILE}"
fi

# ─── Step 2: Add restricted public key to authorized_keys ────
PUB_KEY=$(cat "${KEY_FILE}.pub")

if grep -qF "openclaw-sshfs" "$AUTH_KEYS" 2>/dev/null; then
    echo "✓ Public key already in authorized_keys"
else
    # Restrict: sftp-only, no forwarding, no pty, no commands
    RESTRICTED="command=\"/usr/libexec/sftp-server\",no-agent-forwarding,no-port-forwarding,no-X11-forwarding,no-pty ${PUB_KEY}"
    echo "$RESTRICTED" >> "$AUTH_KEYS"
    chmod 600 "$AUTH_KEYS"
    echo "✓ Added restricted public key to ${AUTH_KEYS}"
    echo "  → Key can ONLY run sftp-server (no shell access)"
    echo "  → No port forwarding, no agent forwarding, no PTY"
fi

# ─── Step 3: Harden sshd_config ──────────────────────────────
echo ""
echo "--- SSH Hardening ---"

if [ -f "$SSHD_CONF" ]; then
    echo "✓ Hardening config already exists at ${SSHD_CONF}"
else
    echo "Creating SSH hardening config (requires sudo)..."
    sudo mkdir -p "$SSHD_CONFIG_DIR"
    sudo tee "$SSHD_CONF" > /dev/null << 'SSHD_EOF'
# OpenClaw SSHFS hardening — generated by setup-sshfs-key.sh
# Disable password auth (key-only)
PasswordAuthentication no
# Limit auth attempts
MaxAuthTries 3
SSHD_EOF
    echo "✓ Created ${SSHD_CONF}"
    echo "  → Password authentication disabled (key-only)"
    echo "  → Max 3 auth attempts per connection"
fi

# ─── Step 4: Check Remote Login status ───────────────────────
echo ""
echo "--- Remote Login Status ---"

if systemsetup -getremotelogin 2>/dev/null | grep -qi "on"; then
    echo "✓ Remote Login (SSH) is enabled"
else
    echo ""
    echo "⚠️  Remote Login (SSH) is NOT enabled."
    echo ""
    read -p "Enable it now? [y/N] " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        sudo systemsetup -setremotelogin on
        echo "✓ Remote Login enabled"
    else
        echo "→ Enable manually: System Settings → General → Sharing → Remote Login → ON"
    fi
fi

# ─── Step 5: macOS firewall note ──────────────────────────────
echo ""
echo "--- Firewall Recommendation ---"
echo "For maximum security, restrict SSH to Docker's subnet only."
echo "Docker Desktop for Mac uses 192.168.65.0/24 internally."
echo ""
echo "To add a pf rule (optional, advanced):"
echo "  1. Create /etc/pf.anchors/openclaw-ssh with:"
echo '     pass in quick proto tcp from 192.168.65.0/24 to any port 22'
echo '     block in quick proto tcp from any to any port 22'
echo "  2. Add to /etc/pf.conf:"
echo '     anchor "openclaw-ssh"'
echo '     load anchor "openclaw-ssh" from "/etc/pf.anchors/openclaw-ssh"'
echo "  3. Reload: sudo pfctl -f /etc/pf.conf"
echo ""

# ─── Summary ──────────────────────────────────────────────────
echo "=== Setup Complete ==="
echo ""
echo "Key:           ${KEY_FILE}"
echo "Authorized:    ${AUTH_KEYS} (sftp-only, no shell)"
echo "SSH hardening: ${SSHD_CONF}"
echo ""
echo "Test from container:"
echo "  docker compose exec openclaw-gateway ssh -i /home/node/.openclaw/sshfs/id_ed25519 \\"
echo "    -o StrictHostKeyChecking=no marcgratch@host.docker.internal echo 'SSH works!'"
echo ""
echo "Note: The restricted key will force sftp-server instead of echo,"
echo "so the test above will show 'This service allows sftp connections only.'"
echo "That means it's working correctly — sftp-only, no shell."
